name: Build S24U Spoofer Magisk Module

on:
  workflow_dispatch:
    inputs:
      samsung_version:
        description: 'Samsung Version'
        required: true
        type: string
      alldevices_version:
        description: 'AllDevices Version'
        required: true
        type: string

jobs:
  build:
    name: Build S24U Spoofer Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Samsung Branch
        uses: actions/checkout@v4
        with:
          ref: samsung

      - name: Build Samsung Version
        run: |
          zip -r S24USpoofer-${{ github.event.inputs.samsung_version }}-SamsungOnly.zip . -x ".git*" -x ".github*" -x "README.md"

      - name: Move Samsung File to Workspace
        run: mv S24USpoofer-${{ github.event.inputs.samsung_version }}-SamsungOnly.zip /tmp/

      - name: Checkout AllDevices Branch
        uses: actions/checkout@v4
        with:
          ref: alldevices

      - name: Build AllDevices Version
        run: |
          zip -r S24USpoofer-${{ github.event.inputs.alldevices_version }}-AllDevices.zip . -x ".git*" -x ".github*" -x "README.md"

      - name: Move AllDevices File to Workspace
        run: mv S24USpoofer-${{ github.event.inputs.alldevices_version }}-AllDevices.zip /tmp/

      - name: Move Files Back to Current Directory
        run: |
          mv /tmp/S24USpoofer-${{ github.event.inputs.samsung_version }}-SamsungOnly.zip .
          mv /tmp/S24USpoofer-${{ github.event.inputs.alldevices_version }}-AllDevices.zip .

      - name: Create a Git Tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag ${{ github.event.inputs.samsung_version }}-${{ github.event.inputs.alldevices_version }}
          git push origin ${{ github.event.inputs.samsung_version }}-${{ github.event.inputs.alldevices_version }}

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: S24U-Spoofer
          path: |
            S24USpoofer-${{ github.event.inputs.samsung_version }}-SamsungOnly.zip
            S24USpoofer-${{ github.event.inputs.alldevices_version }}-AllDevices.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            S24USpoofer-${{ github.event.inputs.samsung_version }}-SamsungOnly.zip
            S24USpoofer-${{ github.event.inputs.alldevices_version }}-AllDevices.zip
          tag_name: ${{ github.event.inputs.samsung_version }}-${{ github.event.inputs.alldevices_version }}
          release_name: S24U Spoofer Module
          body: |
            # S24 Ultra Spoofer Magisk Module  

            üîπ **Samsung Version:** `${{ github.event.inputs.samsung_version }}`  
            üîπ **AllDevices Version:** `${{ github.event.inputs.alldevices_version }}`

            ## ‚ö†Ô∏è Notes  
            - If your device **is not a Samsung**, use the **AllDevices** version.  
            - Remove any previous modifications before installing to avoid conflicts.
